### ISSUE TITLE
ENV variables passed from docker-compose to php-fpm not exposed

### ISSUE THREAD

**Issue by OakBehringer** [phalcon/dockerfiles#14]
Something in your docker-compose.yml like...

```
api-php:
    image: phalconphp/php-fpm:7
    container_name: api-php
    environment:
      - DB_HOSTNAME=somehostname
      - DB_PORT=3306
      - DB_DB_NAME=SomeDbName
      - DB_USERNAME=SomeUser
      - DB_PASSWORD=SomePassword
```

Won't be available in PHP, i.e.: 

`print_r($_ENV); `

is empty. 

PHP-FPM requires `clear_env = no` to be set. See how it is set here, for the same reason:

https://hub.docker.com/r/phpdockerio/php7-fpm/~/dockerfile/

Suggest adding this to your repo, impossible to use as-is.
