### ISSUE TITLE
Php code is displayed instead of executed

### ISSUE THREAD

**Issue by thorakmedichi** [phalcon/dockerfiles#22]
So I have a docker-compose.yml that has this

```yml
phalcon3:
        image: phalconphp/php-apache:ubuntu-16.04
        container_name: phalcon3
        restart: always
        ports:
            - "8888:80"
        volumes:
            - ~/Development/Projects:/projects
            - ~/Development/Docker/logs/apache:/var/log/apache2
            - ~/Development/Docker/etc/apache2/sites-enabled:/etc/apache2/sites-enabled:ro
        environment:
            APP_ENV: development
```

And I have a phalcon-tutorial.conf file like so

```apache
<VirtualHost *:80>
    ServerName phalcon-tutorial.local
    ServerAlias www.phalcon-tutorial.local

    DocumentRoot "/projects/bios/phalcon-tutorial/public"
    DirectoryIndex index.php

    <Directory "/projects/bios/phalcon-tutorial/public">
        Options All
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

    ErrorLog ${APACHE_LOG_DIR}/phalcon-tutorial.error.log
    CustomLog ${APACHE_LOG_DIR}/phalcon-tutorial.access.log combined
</VirtualHost>
```

in my /etc/hosts file
`127.0.0.1   phalcon-tutorial.local`

When I go to phalcon-tutorial.local:8888 in my browser it is just showing the raw php code from index.php

all of the suggestions online involve installing apache mods and editing the httpd.conf file but I would have assumed this should have just worked out of the box when I `docker-compose up`
