### ISSUE TITLE
How to use php-fpm:7?

### ISSUE THREAD

**Issue by cyberhck** [phalcon/dockerfiles#3]
I've not used php-fpm in the past and I'm trying to put together nginx and php-fpm, right now, my docker-compose.yml file looks like this:
```
web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./src:/src
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
php:
  image: phalconphp/php-fpm:7
  volumes:
      - ./src:/etc/php/7.0/fpm/pool.d/
```
and my nginx.conf looks like this:
```
server {
    listen       80;
    server_name  localhost;
    location / {
        root   /src;
        index  index.php;
        autoindex on;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /src;
    }

    location ~ \.php$ {
        index          index.php;
        root           /src;
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME /scripts$fastcgi_script_name;
        include        fastcgi_params;
        autoindex on;
    }
}
```
Now when I go to localhost:8080, it says file not found, nginx finds the file, but it can't process using php-fpm, The error message I get is:

> 2017/02/09 06:09:14 [error] 7#7: *4 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.17.0.4:9000", host: "localhost:8080"

I'm pretty sure I'm doing something stupid, but I can't figure out what.

Can you add something so that I can go forward with.

Thanks

**Comment by sergeyklay** [comment]
Hm... did you tried something like this?

```yml
version: '2'

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: phalcon_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: phalcon_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
      
  php:
    restart: always
    image: phalconphp/php-fpm:7.0
    container_name: phalcon_php
    working_dir: /app
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./src:/app
    depends_on:
      - mysql

  nginx:
    restart: always
    image: phalconphp/nginx:1.1.0
    container_name: phalcon_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/mysite
      - ./nginx.conf:/etc/nginx/sites-enabled/my-site.conf
    depends_on:
      - php

# docker volume create --name=mysql
volumes:
  mysql:
    external: true

# docker network create --driver bridge phalcon_nw
networks:
  default:
    external:
      name: phalcon_nw
```
